### PR TITLE
Release/0.2

### PR DESCRIPTION
**Pull request by DJ2513**

### CODE REVIEW

**Comment by herrerpm** [comment]
The work we have done here it is awesome, beautiful architecture, excellent usage of desing patterns. It is a keystone on good practices, great work guys!

**Review by herrerpm — APPROVED** [review]
LGTM

**Review by GabrielGuerra06 — APPROVED** [review]
This is an outstanding implementation and a huge demonstration of team work, collaborative project and a pleasure to share

**Review by DanielRPrado — COMMENTED** [review]
Excellent work, I'm proud of you.

**Pull request merged**
